- utils/translator/readme.md
- utils/translator/translator.js
- utils/translator/translator.test.js
This is a translator utility that we can reuse in many different place here's how it works. If You have the following translations
``` javascript
const exampleTranslations = {
'simple': {
en: 'Hi, Tester',
sw: 'Niaje, Tester'
},
'another': {
fr: 'bonjour',
de: 'Guten tag'
},
'preferred-name-prompt': {
en: 'Should I call you $firstName or $lastName',
sw: 'Ninapaswa Kukuita $firstName au $lastName',
}
};
```
you can create a translator out of it as follows
``` javascript
const createTranslator = require('./translator');
const translate = createTranslator(exampleTranslations)
```
and then get translations like this
```javascript
const englishText = translate('preferred-name-prompt','en',{ '$firstname': 'Peter', '$lastName': 'Parker'});
```
> Global translations

- utils/translator/translator.js
- utils/translator/translator.test.js
currently the translator utility is called like this 
call(key, lang, options)
changed it to
call(key, options, lang)
purpose. 
this is for better implementation when we want to omit the lang since it is sometimes set to default hence optional.
> Refactoring of the translator utility

- rw-legacy/core.js
The user was entering the number of farmers in the group in 'market_people_in_group' input handler but wasn't been saved in the results data table. This fixes it.
> saving the number of farmers entered by the user in a table

- ke-legacy/main.js
- transaction-history/id-verification/index.js
- transaction-history/index.js
- transaction-history/list-transactions/index.js
- transaction-history/translations.js
- utils/translator/translator.js
- utils/translator/translator.test.js
this adds transaction history support for Kenya.
It also adds support for locale based translations such that `en-ke` can fallback to `en` if not assigned.
Also adds some basic dev and production environments for Kenya as well
Test it using account `22846955` with national ID number ending with `6866` you can test it here: https://telerivet.com/p/0c6396c9/service/SV7a3fa65de30127c9/edit
> Add transaction history support to Kenya

- rw-legacy/extension-survey.js
- rw-legacy/lib/ext-resume-survey.js
SI-478 allow testing with dummy village Ids(10000000 and 11111111) for the RW extension registration service
SI-477: add saving the village ID, Sector, and Cell.
Extension registration context: Appears as no1 on the menu, prompt for basic information, with questions afterward. All the answers should be yes except the second one for the farmer to be eligible and saved in the 'Extension Farmers' data table.
This PR makes sure that if 10000000 is entered as village ID, the resume session doesn't work in order to allow multiple people to use it in testing at the same time. It also saves additional information in the table for successful farmers. 
It can be tested here: https://telerivet.com/p/4bee87c0/service/SV80c59c2e64f4fe9d/edit
> Si 478 allow testing with dummy data

- duka-receipts/dukaReceipts.js
- duka-receipts/dukaReceipts.test.js
this is due to the use of **netUnitPrice** instead of **unitPrice**
you can test from [here](https://telerivet.com/p/070b4dfe/service/SVa812d22fe05420dd)
> fixing the bug that some vat cost becomes negative

- duka-receipts/dukaReceipts.js
- duka-receipts/dukaReceipts.test.js
The calculations mentioned in the past ticket were slightly off. After confirming with the stakeholder, they should be updated to:
Total cost = amount = sum of all **row prices** = eg: 220.05
Product cost = sum of all **net row prices** for every product = eg: 193.03
VAT = total cost - product cost = 220.05 - 193.03 = 27.02
Test from [Telerivet](https://telerivet.com/p/070b4dfe/services?mode=d&sort=name&f[status]=0&f[trigger_id]=2)
> Modify receipt field calculations

- duka-receipts/dukaReceipts.js
- duka-receipts/dukaReceipts.test.js
The stakeholder would like for the "total" field on duka receipts to be rounded to the nearest zero, as that will make it match our POS system. Please find an example below:
... other part of the message ....
**Total: Ksh.1150.00** (this is rounded from **1150.16**)
> Update the "total" field on the receipts so that it's rounded to the nearest zero

- ke-legacy/main.js
at some moments, when the menu gets to more than one page, it became an **object** instead of a **string**. This fix makes sure that right menu (string) is assigned to the state variable.
This is in response to ticket SER-168. users were not able to access the group summary option on the menu, but it turns out the issue is that the accounts used were not group leaders in the current season.
> fixing assinging a non stringified objects to the state variable

- tester-pack/confirmation/inputHandlers/villageHandler.js
- tester-pack/confirmation/inputHandlers/villageHandler.test.js
- tester-pack/confirmation/translations/index.js
https://telerivet.com/p/4bee87c0/service/SVa2e7a19f20dc2bc8/edit
**demonstration**
- dial the short code
- choose tester pack (3)
- choose confirmation (2)
there will be a list of provinces in Kinyarwanda instead of the previous behaviors where provinces were in english
_________________________________________________________________
https://telerivet.com/p/4bee87c0/service/SVa2e7a19f20dc2bc8/edit
this usually given **undefined** but it is now notifying the user that the selected village has no farmer
**demonstration**
- dial the short code
- choose tester pack (3)
- choose confirmation (2)
- choose any district other than KIgali since only one sector in Kigali has test data.
- continue choosing on options give. at the end, after choosing a village, you should receive a notice that the …
> Bg fix tester pack

- rw-legacy/extension-survey.js
- tester-pack/confirmation/inputHandlers/receptionHandler.js
- tester-pack/confirmation/inputHandlers/receptionHandler.test.js
updated the 'Extension Farmers All candidate' to stored these columns in addition: First Name, Last Name, Gender, National Id, Phone Number. Registration Status, Received Tester Pack, Sector, cell, Village, Village ID, Time Created | Last Updated(registration and confirmation)
testing link: https://telerivet.com/p/4bee87c0/service/SV80c59c2e64f4fe9d/edit
registration steps:
- select option 3 on the main menu
- select option 1 on the second menu
- for village Id you can use: 53040303
- any name(first name and last name)
- any valid phone number(eg:0786182098)
- any valid national Id (eg:1199780043907055)
- answer all question yes, except the second one to no(for a valid request) **for an invalid answer any question no except qn2**
The above columns should be saved
-confirmation steps:
- …
> SER-150 restructured the all candidate extension table

- rw-legacy/core.js
- recently, users could only retrieve solar payg code if and only if they have met the payment threshold
- currently, users can retrieve the solar payg code regardless of their balance
[Finishes #SER-197]
Test from 
Account number: 18659550
**old implementation**
https://telerivet.com/p/8799a79f/service/SV0f1e9ba5632d5274/edit
this should not give the payg code since the account 18659550 has not paid to the threshold payment. instead it should give a message about user being unable to retrieve the paygcode.
**new implementation**
https://telerivet.com/p/8799a79f/service/SV215b0cbe269df25d/edit
since the condition has been eliminated, you can now get the paygcode for this user.
> (hotfix) fixing the solar payg code retrieval

- client-enrollment/clientEnrollment.js
- client-enrollment/test.js
- client-enrollment/translations.js
- client-registration/clientRegistration.js
- client-registration/national-id-handler/nationalIdHandler.js
- client-registration/test.js
- client-registration/translations.js
SER-182-prevent-new-clients-from-being-enrolled-multiple-times:
-Added a check for national Id in the client's table when a user is registering and a check for a duplicate account number when a user is enrolling.
Testing link: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
Steps: 
- Enter an account number: 24450523
- Select 3 on the next menu (enroll) 
- enter an account number: 26931220 ** It should prevent you from registering and display a message **
for registration:
- Enter an account number: 24450523
- select  3 for enrollment
- enter zero for new client registration
- enter a used national Id 98765432 ** It should prevent you from registering and display a message with your account number **
> prevent multiple enrollments

- client-enrollment/clientEnrollment.js
- client-enrollment/test.js
- client-enrollment/translations.js
- client-registration/clientRegistration.js
- client-registration/national-id-handler/nationalIdHandler.js
- client-registration/test.js
- client-registration/translations.js
This PR was merged in develop but is needed on master as hotfix(SER-200)
SER-182-prevent-new-clients-from-being-enrolled-multiple-times:
-Added a check for national Id in the client's table when a user is registering and a check for a duplicate account number when a user is enrolling.
Testing link: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
Steps:
Enter an account number: 24450523
Select 3 on the next menu (enroll)
enter an account number: 26931220 ** It should prevent you from registering and display a message **
for registration:
Enter an account number: 24450523
select 3 for enrollment
enter zero for new client registration
enter a used national Id 98765432 ** It should prevent you from registering and display a message with your account number **
> Ser 182 prevent new client from being enrolled multiple times

- duka-locator/inputHandlers/dukaHandler.js
- duka-locator/translations/index.js
Fixing duka locator -KENYA
[Old implementation](https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0)
- After selecting the duka, you are prompted to whether to reach out to the duka agent(which is sending them a message). This screen has a title which is supposed to be the address of the selected duka. However, it now display undefined due to the collision of language 'en' and 'en-ke'.
[New implementation](https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit)
- Dial the short code
- enter the account number (**26215997**)
- select Locate OAF Duka (option 10 on screen 2)
- go through the process until you reach the dukas.
- select one of the listed dukas
- there should come a screen asking you whether to reach out to that duka's agent.
This screen should have a title …
> Fixing duka locator

- rw-legacy/extension-survey.js
Added a column of the district to the extension Farmers table as well as the extension farmers all candidates
link for testing: https://telerivet.com/p/4bee87c0/service/SVa69cf6f145781fff/edit
- Choose option 3 from the main menu
- Choose registration as option 1 on the second menu
- Enter **11111111** as the village ID
- Enter valid farmer information(eg: 16 digits for ID, 10 digits for phone number)
- Answer the questions (2**oya** for the second question and 1**yego** for the others) for a successful registration
The district column should contain the district name for the chosen village in the 'dev_extension farmers all candidate' and 'dev_extension_farmers' tables
> SER-215 added a district column to the tables

- tester-pack/confirmation/inputHandlers/cellHandler.js
- tester-pack/confirmation/inputHandlers/cellHandler.test.js
- tester-pack/confirmation/inputHandlers/districtHandler.test.js
- tester-pack/confirmation/inputHandlers/districtsHandler.js
- tester-pack/confirmation/inputHandlers/farmerHandler.js
- tester-pack/confirmation/inputHandlers/farmerHandler.test.js
- tester-pack/confirmation/inputHandlers/sectorsHandler.js
- tester-pack/confirmation/inputHandlers/sectorsHandler.test.js
- tester-pack/confirmation/inputHandlers/villageHandler.js
- tester-pack/confirmation/inputHandlers/villageHandler.test.js
- tester-pack/confirmation/translations/index.js
- tester-pack/status/inputHandlers/nextScreenHandler.test.js
- tester-pack/status/inputHandlers/nextScreensHandler.js
- tester-pack/status/inputHandlers/registeredConfirmed.test.js
- tester-pack/status/inputHandlers/registeredConfirmedHandler.js
- tester-pack/translations/index.js
Fixing tester pack.
- currently when a user is confirming the reception or checking the status of tester pack, the locations tends to be many hence the list is divided into screens.
- User is given an option to select * to go to another screen. the service works well but due to some reasons suspecting that different phones treats ***** differently, I have changed the option to 77 instead of *.
https://telerivet.com/p/4bee87c0/service/SVa2e7a19f20dc2bc8/edit
**1. confirmation**
*Navigation on telerivet*
- Dial in the shortcode
- From the main menu, choose tester pack as **option 3**
- On the displayed menu, chose confirmation which is available on **option 2**
- On the list of provinces, choose Kigali from **option 2**
- On the list of Districts, choose Nyarugenge available on **option 1** …
> hot fix: fixing tester pack confirmation

- just-in-time/account-number-handler/accountNumberHandler.js
- just-in-time/account-number-handler/accountNumberHandler.test.js
- just-in-time/justInTime.js
- just-in-time/justInTime.test.js
- just-in-time/test-client-data.js
- just-in-time/translations.js
- ke-legacy/main.js
- ke-legacy/utils/menus/populate-menu/mainMenu.js
- ke-legacy/utils/menus/populate-menu/populateMenu.js
As a GL, I want to be able to top up a client's order via USSD, so that I can adjust orders prior to distribution (PART 1)
The first menu that deals with checking if the client is a group leader and that he wants to top up for a valid account number in their group.
Link for testing: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
Steps:
Log in with the account number: 24450523
Should see option 4(top Up)-- choose it
**Enter an account number in the same group**
- 24450523 (should see a message saying how much they need to pay)
- use 26965613 for another account number in the same group
**Repeat the same process with an account number, not in the same group**
- use 16532926. should prompt the user for an account number in the same group
> added the first menu for just in time

- duka-locator/inputHandlers/countyHandler.js
- duka-locator/translations/index.js
- group-repayments/inputHandlers/groupSummaryHandler.js
- group-repayments/inputHandlers/groupSummaryHandler.test.js
- group-repayments/inputHandlers/individualBalanceHandler.js
- group-repayments/inputHandlers/individualBalanceHandler.test.js
- group-repayments/inputHandlers/lastFourIdDigitsHandler.js
- group-repayments/inputHandlers/lastFourIdDigitsHandler.test.js
- group-repayments/translations/message-translations.js
the same issue with tester pack.
duka locator and group repayments have * and # as options of navigating the screen. I have changed them to 77 and 44 respectively.
duka locator: https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
GROUP leader RW: account number: **28951336**
group repayments RW: https://telerivet.com/p/8799a79f/service/SV215b0cbe269df25d
group repayments: KE: https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit 
these services should behave exactly as before but with * and # replaced with 77 and 44 respectively
> Fix screens navigation

- Roster-endpoints/enrollOrder.js
- Roster-endpoints/enrollOrder.test.js
- just-in-time/add-order-handler/addOrderHandler.js
- just-in-time/add-order-handler/addOrderHandler.test.js
- just-in-time/bundle-choice-handler/bundleChoiceHandler.js
- just-in-time/bundle-choice-handler/bundleChoiceHandler.test.js
- just-in-time/justInTime.js
- just-in-time/justInTime.test.js
- just-in-time/order-confirmation-handler/orderConfirmationHandler.js
- just-in-time/order-confirmation-handler/orderConfirmationHandler.test.js
- just-in-time/translations.js
- just-in-time/utils/populate-bundles.js
- just-in-time/utils/populate-bundles.test.js
- just-in-time/variety-choice-handler/varietyChoiceHandler.js
- just-in-time/variety-choice-handler/varietyChoiceHandler.test.js
- just-in-time/variety-confirmation-handler/varietyConfirmationHandler.js
- just-in-time/variety-confirmation-handler/varietyConfirmationHandler.test.js
- ke-legacy/main.js
Allow group leaders to top up clients' orders.
- Use a group leader account to login: 24450523
- choose option 4: top up on the menu
- enter an account number in the same group(26967747 for someone that meets prepayment conditions)(26967403: someone who doesn't meet prepayment condition)
- choose a bundle to top up(if the bundle has varieties you will then be prompt to choose a variety)
- choose to add products or finalize your order
- you should receive an sms when you finalize your order and the order is saved in Roster
Note that only 2 products can be ordered at the same time, and only one of them should be maize
Test link: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
It can be reviewed through commits: [here](https://github.com/one-acre-fund/ussd-sms/pull/116/commit …
> Ser 9 184 final

- chicken-services/chicken-eligibility/chickenEligibility.js
- chicken-services/chicken-eligibility/chickenEligibility.test.js
- client-registration/clientRegistration.js
- client-registration/clientRegistration.test.js
- rw-legacy/extension-survey.js
**SER-231** Update the data collection to store district and site names instead of IDs
Follow the client registration steps:
- Enter a GL account number: 24450523
- Choose option 3 register client(there are two now because when the second one go live we will remove the first one)
- Choose 0 to register a new client
- Enter any 8 digit number as national ID 
- Enter any names(first and last)
- Enter a phone number: 0712301351
- choose any option for GL interest
**It should now save the district name and the site name in the registration table** [here](https://telerivet.com/p/0c6396c9/data/dev_5Flr_5F2021_5Fclient_5Ftable)
Test service link: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
**SER-232** Ensure that chicken prepayment and monthly cap logic is working correctly …
> Hotfix ser 230 ser 229

- chicken-services/possible-order-handler/possibleOrderHandler.js
- chicken-services/possible-order-handler/possibleOrderHandler.test.js
- ke-legacy/main.js
SER- 233: **Prevent chicken clients from ordering partial chickens**
- Added a check to see if the user entered a whole number. prompt them to retry if not
SER-234: **Add ward name to FO_Locator_Prospects data table**
- Saving ward name in the dataTable of FO_Locator prospect
Steps to test:
- Enter 0 instead of an account number
- Choose 1 on the next menu for Locate FO
- Choose 1 for the next menus until reached to the ward selection
- Choose 1 for ward(Riakanau in this case) then 1 for site (Riakanau  in this case)
- Choose 1 to approve FO to reach out to you
A row should be saved in this table [FOProspectTable](https://telerivet.com/p/0c6396c9/data/FO_5FLocator_5FProspects) with the ward name included
-Test link: https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit
> Ser 233 234 add ward name digit chicken number

- ke-legacy/main.js
- ke-legacy/utils/menus/populate-menu/nonClientMainMenu.js
- ke-legacy/utils/menus/populate-menu/test.js
updated the message on the main non-client menu as well as the select location menu.
Added a step for prompting the national ID then save it to the Prospects clients dataTable
- Choose 0 to access a non-client menu
- Choose 1 to find Fo
- Enter a national ID
- Confirm
- Go to any location
- At the end it will save the info including the national ID [here](https://telerivet.com/p/0c6396c9/data/FO_5FLocator_5FProspects)
Test link: https://telerivet.com/p/0c6396c9/service/SV52afe381873857ad/edit
> update FOLocator message and add national Id step

- repayments/repayments.js
- repayments/repayments.test.js
- adding the labels to the messages sent
The current repayment and shs notifications messages do not have labels attached. so with this fix, all sent messages have labels attached.
> HOT-FIX-SER-236 adding the labels to the messages sent

- rw-legacy/lib/account-verify.js
when login fails if the client Balance history and Account History are too big, this change reduces the size of both to  at most 3. To test that it works try login with the account **16064324** [ at this service](https://telerivet.com/p/0c6396c9/service/SV7a3fa65de30127c9/edit) that login fails in the main [test service](https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit) and production
> SER-240 - HOTFIX - reduce the size of account and  balance history

- CHANGELOG.md
- just-in-time/justInTime.js
- just-in-time/justInTime.test.js
- just-in-time/translations.js
update to send an SMS to the stored client's phone number in addition to the phone being used when placing an order for  just in time [SER-9](https://oneacrefund.atlassian.net/secure/RapidBoard.jspa?rapidView=83&selectedIssue=SER-9), update the content to include the ordered products as well 
To test: Dial on this service [here](https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit) 
- Enter a GL account: **24450523**
- Choose 5 for top-up on the net menu
- Enter an account number in the same group: **27507822** or **27507840**
- Place any order and finalize
- Confirm
- Two SMS should be sent (on the phone being used and Angello's Kenya SIM)
> added sending an sms to the client stored phone number in just in time

- ke-legacy/main.js
The error occurs when newly registered clients that have no balance history try to access the make payment menu item. 
It is safe to set the repaid and balance values to 0 when the balance history length is 0
> fix SeasonName undefined error

- CHANGELOG.md
- client-registration/first-name-handler/firstNameHandler.js
- client-registration/first-name-handler/firstNameHandler.test.js
- client-registration/second-name-handler/secondNameHandler.js
- client-registration/second-name-handler/secondNameHandler.test.js
- rw-legacy/core.js
This PR adds names validations before making a call to roster registration API, to avoid special characters which currently leads to errors
> HOTFIX-SER-244-remove special characters from names during registration

- CHANGELOG.md
- rw-legacy/core.js
- rw-legacy/lib/utils/message-translations.js
Before the first menu for Rwanda core was:
Welcome to One Acre Fund Tubura.\n**0**) Not currently a client\n**1**) Already a client
changed it:
to Welcome to One Acre Fund Tubura.\n**1**) Not currently a client\n**2**) Already a client**
It looks like 0 doesn't work on the first menu
If you have a Rwanda SIM you can test it on develop : \*801\*15# (old code)
or on the shortcode \*801\*13#(this branch)
> hotfix- fixing the rwanda main menu issue

- CHANGELOG.md
- duka-client/registration/inputHandlers/accountNumberInputHandler.js
- duka-client/registration/inputHandlers/accountNumberInputHandler.test.js
- duka-client/registration/inputHandlers/confirmFirstSecondNameInputHandler.js
- duka-client/registration/inputHandlers/confirmInvoiceIdInputHandler.js
- duka-client/registration/inputHandlers/firstNameInputHandler.js
- duka-client/registration/inputHandlers/firstNameInputHandler.test.js
- duka-client/registration/inputHandlers/secondNameInputHandler.js
- duka-client/registration/inputHandlers/secondNameInputHandler.test.js
- duka-client/registration/translations/index.js
TEST FROM [HERE](https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit)
- dial is the short code
- enter a credit officer id: 1234
- choose register client (option 1)
- choose 0 for new client
- respond to all prompts
(national id is any 7 or 8 digits number)
- for others you can enter any generic input.
for the sake of demoing the sms sent, you can put the simulator phone(555-0123) when prompted for phone so that the simulator will receive the sms.
user should be registered and sms should be sent notifying the user of their new account number.
- enter the officer id (1234)
- choose register client (option 1)
- enter the account number (27508860)
- there comes a notice that a client is not a duka district client
- choose 0 attempting to register them as …
> HOT-FIX duka client registration

- CHANGELOG.md
- Roster-endpoints/Fo-info/getFoInfo.js
- Roster-endpoints/Fo-info/getFoInfo.test.js
Fixed the issue of sending an SMS with FO contact
To test here:  https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit
- use 24450523 as account number
- choose 3 for client registration
- choose 0 for a new client
- enter any 8 digits national ID, 
- enter 0712301351 as phone number
- finalize registration
- an SMS should be sent with FO contact
the same step bringing the FO contact here: https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit
> THD-3170-fixed getFOInfo return value

- CHANGELOG.md
- avocado-trees-ordering/avocadoTreesOrdering.js
- avocado-trees-ordering/avocadoTreesOrdering.test.js
Save the difference between the ordered avocado and what the user just confirmed in a separate column instead of overwriting the old column
To test: https://telerivet.com/p/8799a79f/service/SV1161debc042a9de0/edit
- enter 2 on the first menu for returning client
- use the account number: 27842919
- choose option 7(order avocado)
- order any amount of avocado greater than 3
- confirm the order
**the avoka_jit column should be updated with the difference between the a_avokaqty( ordered quantity) column and the value confirmed**  [here](https://telerivet.com/p/8799a79f/data/dev_5Favocado_5Ftable?sort=&f[vars.account_number]=27842919)
> SER-268-added saving the diference between the orders to another column

- CHANGELOG.md
- rw-legacy/lib/roster/register-client.js
Updated the registration service to reflect the changes of its endpoint(returning the account number as a key-value instead of a string)
To test it here: https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit
- use the account number 24450523
- choose option 3 to register a client
- Enter 0 for a new client
- Enter an already registered national ID:3198116
- Continue with the registration process, for the phone number you can use: 0712301351
- An message with the registered account number should be displayed on the phone
> hotfix-update the registration endpoint to match the endpoint change

- client-registration/second-name-handler/secondNameHandler.js
- client-registration/second-name-handler/secondNameHandler.test.js
- rw-legacy/core.js
Service: https://telerivet.com/p/8799a79f/service/SV0990ef3092d2c138/edit
1. Dial \*801\*13#
2. Enter 1 to select the _Not currently a client_ option
3. Enter a 16 digit national ID
4. Enter 1 to confirm the national ID
5. Enter first name
6. Enter a **non-alphanumeric string** as second name
7. Complete the rest of the enrolment steps
8. The client should be registered with the second name set to `XXXXXX`
> Add "XXXXXXX" to the second name automatically

- CHANGELOG.md
- duka-client/registration/inputHandlers/accountNumberInputHandler.js
- duka-client/registration/inputHandlers/accountNumberInputHandler.test.js
- duka-client/registration/inputHandlers/confirmFirstSecondNameInputHandler.js
- duka-client/registration/inputHandlers/confirmInvoiceIdInputHandler.js
- duka-client/registration/inputHandlers/secondNameInputHandler.js
- duka-client/registration/inputHandlers/secondNameInputHandler.test.js
- duka-client/registration/inputHandlers/transactionTypeInputHandler.js
- duka-client/registration/inputHandlers/transactionTypeInputHandler.test.js
- duka-client/registration/registration.js
- duka-client/registration/registration.test.js
- duka-client/registration/translations/index.js
TEST FROM HERE https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
Dial in the short code:
- enter the credit officer code: 1234
- select 1 for registration
- enter account number:  non duka: **28126250**  or duka: **28126275 **
before implementing the changes, user received a prompt for invoice id but now,
- user receives a prompt to enter transaction type
- choose any of the two on the screen
- enter the invoice id: any number
- confirm
- a record should be created in https://telerivet.com/p/0c6396c9/data/dev_5Fduka_5Fclient_5Fregistration
with all user information
The same case for new clients.
- enter the credit officer code: 1234
- select 1 for registration
- choose zero for new client
- answer all prompts. after entering the second name, you should receive a prompt for …
> HOTFIX-Ser 274 update duka registration

- CHANGELOG.md
- duka-client/registration/inputHandlers/accountNumberInputHandler.js
- duka-client/registration/inputHandlers/accountNumberInputHandler.test.js
- package-lock.json
- package.json
allow accounts with the district name: OAF Duka
to test here: https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit
- enter 1234 on the first menu
- enter 1 to register the client
- enter any account number on the ticket:
26916340
26916354
26916412
26916420
26916436
26916448
26916457
26916473
26916485
26916499
26916500
It should show a message confirming it's a duka account
> hotfix ser-335 allow duka districts

- CHANGELOG.md
- duka-client/registration/inputHandlers/accountNumberInputHandler.js
- duka-client/registration/inputHandlers/accountNumberInputHandler.test.js
- package-lock.json
- package.json
Currently when a credit officer registers a core client who has some loan to a duka district, they are told to complete that loan.
The correction is that we only require that for already existing duka clients who have loans.
testing: https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit
- Dial in the shortcode
- Add the credit officer id: 1234
- Enter 1 for registration
- Add account number (`29304074`) the core client with credit
```  "BalanceHistory": [
{
"AccountGuid": "guid",
"GroupId": 1270,
"GroupName": "name",
"SiteId": 19,
"SiteName": "site name",
"SeasonId": 280,
"SeasonName": "season name",
"SeasonStart": "2021-03-01T00:00:00",
"TotalCredit": 14286.000,
"TotalRepayment_IncludingOverpayments": 0.0000,
"Balance": 14286.0000,
"CurrencyCode": "KES"
}
- Enter Zero (0) to …
```
> HOT-FIX SER-349 Change USSD response for core clients who would want to be enrolled at the Duka

- CHANGELOG.md
- healthy-path/balance/healthyPathOnBalance.js
- healthy-path/balance/healthyPathOnBalance.test.js
- healthy-path/repayments/HealthyPathOnRepaymentReceipts.js
- healthy-path/repayments/healthyPathOnRepayments.test.js
- healthy-path/utils/getHealthyPathPercentage.js
- healthy-path/utils/getHealthyPathPercentage.test.js
- repayments-rw/repaymentsRw.js
- repayments-rw/repaymentsRw.test.js
- repayments-rw/translations/index.js
- repayments/repayments.js
- repayments/repayments.test.js
when the healthy path result is empty the repayment and check balance information could fail or send a message containing NaN or undefined but now, when there is no healthy path returned, there is no healthy path message returned.
> MOB-109 fix healthy path

- CHANGELOG.md
- client-enrollment/clientEnrollment.test.js
- client-registration/bundle-choice-handler/bundleChoiceHandler.test.js
- client-registration/clientRegistration.js
- client-registration/clientRegistration.test.js
- client-registration/continue/continue.js
- client-registration/continue/continue.test.js
- just-in-time/account-number-handler/accountNumberHandler.test.js
- just-in-time/bundle-choice-handler/bundleChoiceHandler.test.js
- just-in-time/justInTime.js
- package-lock.json
- package.json
(https://oneacrefund.atlassian.net/browse/MOB-156)
Updated the KE registration to check the warehouse before showing the products to the user just like JiT service
To test here: https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit
Dial with the account number 13983972
- Choose option 3 for registration
- Enter 0 for registering a new client 
- Enter any 8 digit national ID
- Enter any First and last name
- Use any phone number starting with: 07**********
- Enter 1 to continue
The list showing up matches products available in the Bungoma district on this [table](https://telerivet.com/p/0c6396c9/data/dev_5FJIT_5FWarehouse_5Fstock?sort=&f[vars.warehousename]=Bungoma+Three)
Finish ordering, the chosen products should be incremented on ordered column on the above table
> HOTFIX- MOB-156-Warehouse stock count debug

- CHANGELOG.md
- package-lock.json
- package.json
- rw-legacy/core.js
- rw-legacy/lib/utils/message-translations.js
Removes product list redirection menu from the registration as people shouldn't be confirming orders
To test: [here](https://telerivet.com/p/8799a79f/service/SV1161debc042a9de0/edit)
Press 1 to register a new client
Go through registration steps: 16 digits national Id, for group code: 32646*008*00312
you shouldn't be redirected to product list
> HOTFIX-Removed ordering redirection

- CHANGELOG.md
- package-lock.json
- package.json
- rw-legacy/lib/psh-reg-check.js
- rw-legacy/lib/psh-renew-code.js
- rw-legacy/lib/psh-serial-verify.js
currently, the clients are unable to get activation codes, due to the way the new activation codes were uploaded without the `type` column. I have changed this to keep use of `unlock` column to be Yes or No instead of relying on both unlock and type.
I have also commented out the check for type='biolite' since all products are now biolite and some of the products do not have the value `biolite` by default.
> HOTFIX: fixing the pshop shs activation

- CHANGELOG.md
- package-lock.json
- package.json
- shs/endpoints/registerSerial.js
Before a serial number containing letters like: SHX-14788199 was being validated on the endpoint but not in Telerivet. This resulted with a message saying "USSD request received" instead of prompting for another input. This PR corrects that.
To Test [here](https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit):
Enter account number: 25069548
Choose Solar option
Choose Register shs: 1
Choose new SHS: 1
Enter a wrong shs unit: SHX-14788199
You should be prompt to enter another one
The same fails on the test/live service: [here](https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit)
> MOB-407-Handle invalid shs

- kenya-impact-trainings/translations/index.js
currently the popup after selecting the training is  changed to the next message for swahili
```
Hongera [farmer's name] kwa hatua yako ya kwanza kuelekea kuwa mkulima mwenye maarifa!
Ujumbe wa mafunzo umetumwa kwa simu yako. Anza safari yako ya kujifunza sasa.
```
dial in the ussd
https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit
- enter 99 to change to swahili
- enter 0 to access the non clients menu
- choose 2 for trainings
- enter phone: 0700010006 to access trainings menu
- the order of trainings on the menu should be
```
1:Kupanda Mahindi/Maharagwe
2:TopDress
3:Wadudu/Magonjwa
4:Kuvuna Mahindi
```
and not any other order
and upon selecting any training, there should be a popup message as shown above if you have choosen swahili
> Fixing popup translation
