.eslintrc.js, package-lock.json, package.json
This adds eslint to the repo, including commands to fix some fixable errors. 
- To trigger linting `npm run lint`
- To lint and fix fixable errors run `npm run lint:fix`
- To continuously lint while developing, install the [eslint extension ](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
=> Adds eslint

.eslintrc.js, package.json, rw-legacy/lib/admin-alert.js, setupTests.js, slack-logger/index.js, slack-logger/test.js
This adds support for slack notifications via webhooks to telerivet.
It also sends admin alerts to the slack instead of just email.
=> Slack notifications for telerivet

rw-legacy/core.js, rw-legacy/lib/core-group-size-check.js, rw-legacy/lib/utils/message-translations.js
SI-454: After the clients enter their group id both in registration and enrollment, We check if the current number of clients is below 16 before allowing them to join the group
=> added restriction of group size to 16

rw-legacy/core.js, rw-legacy/lib/populate-menu.js, rw-legacy/lib/utils/message-translations.js
Change the user flow for the market access option(for group leaders):
- Removed the input handler for crop option
- Removed the input handler for price
- Changed menu messages
- restricted the number of persons to order to 30
- restricted the possible amount to 0 - 1000000
=> Si 456 user flow updated

rw-legacy/core.js, rw-legacy/cta.js, rw-legacy/dat/rwanda-gov-geography.js, rw-legacy/lib/utils/message-translations.js
SI-460: updated the 'rwanda-gov-geography' file, updated the maximum input digit to 2
SI-461: updated a message translation in the maize market service
=> SI-460 phone number not showing correctly

rw-legacy/core.js, rw-legacy/lib/get-menu-option.js, rw-legacy/lib/populate-menu.js
SI-470: removed group leade restrictions for the market access service
=> remove GL restrictions for market access

rw-legacy/core.js
Changed the "market access Info" table ID to a new one as the old one was deleted
=> market access table fix

duka-locator/index.js, duka-locator/index.test.js, duka-locator/inputHandlers/contactDukaAgentHandler.js, duka-locator/inputHandlers/contactDukaAgentHandler.test.js, duka-locator/inputHandlers/countyHandler.js, duka-locator/inputHandlers/countyHandler.test.js, duka-locator/inputHandlers/dukaHandler.js, duka-locator/inputHandlers/dukaHandler.test.js, duka-locator/inputHandlers/regionHandler.js, duka-locator/inputHandlers/regionHandler.test.js, duka-locator/translations/index.js, ke-legacy/main.js, ke-legacy/translations/index.js, ke-legacy/utils/build-menu.js, ke-legacy/utils/buildMenu.test.js, setupTests.js
A client or prospective client can access the duka location functionality fro Kenya
- on the splash menu, clients farmers are required to enter their account numbers and non-client farmers are required to enter zero
- they are presented with their menu including locating an oaf duka
- once they choose it, they are directed into steps to locate the duka and contact the duka supervisor
- duka supervisors are notified once a farmer contacts them.
- farmers receive a message with the supervisor's information
Dev info
-  you can use this account `10477597` to test on [telerivet](https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0)
```
finishes SI-465
finishes SI-464 
finishes SI-463
=> Duka location

rw-legacy/core.js, rw-legacy/lib/utils/message-translations.js
SI-478 : Due to the RW enrollment period ending, this PR comments out the registration step and change the message of the main menu accordingly
=> SI-478 removed registration from the menu

chicken-services/change-order-confirmation/index.js, chicken-services/change-order-confirmation/test.js, chicken-services/change-order-handler/index.js, chicken-services/change-order-handler/test.js, chicken-services/chicken-eligibility/index.js, chicken-services/chicken-eligibility/test.js, chicken-services/index.js, chicken-services/place-order-handler/index.js, chicken-services/place-order-handler/test.js, chicken-services/possible-order-handler/index.js, chicken-services/possible-order-handler/test.js, chicken-services/test-client-data.js, chicken-services/test.js, chicken-services/translations.js, package-lock.json, package.json, rw-legacy/core.js, rw-legacy/lib/backToMainMenu.js, setupTests.js
SI-331: As a client, I want to confirm my chicken order via USSD, so that I can make sure my order is placed  
- The client chooses an option of confirming chicken order(currently option 5)
- If the client already confirmed the order, display how many they have confirmed then ask if they want to change their order
- If they want to change, display how many they are eligible for, given their repayment( minimum--> (if repayment>1000))
- If they have not placed the order, provide them with a menu asking them if they would like to place an order
- Save their order in a data table
SI-466: Differentiate orders confirmed before 1st October to those that happened after
Testing the service: https://telerivet.com/p/8799a79f/service/SV0f1e9ba5632d5274/edit 
Account number: 24450523
=> SI-331 Chicken confirmation services

duka-receipts/dukaReceipts.js, duka-receipts/dukaReceipts.test.js, duka-receipts/objectKeysFilter.js, duka-receipts/objectKeysFilter.test.js, setupTests.js
**Updating the duka receipt sent via the message**
_Currently user receives the following information_
- Product cost
- date and the receipt number
_After completion user receives_
- Product cost
- Date
- Receipt number
- VAT cost and Total cost
***KE Duka program***
**dev notes**
Test from this [Telerivet Service](https://telerivet.com/p/070b4dfe/service/SVa812d22fe05420dd)
this service receives a payload when triggered. that payload is automatically loaded into the state and accessed by `state.vars`
to test it, you will need to uncomment a line at the top of telerivet script so as to mock that payload, and them click on simulate service on the device simulator
**expectations after testing**
the simulator should receive a message like this
```
Thank you for shopping at the OAF Duka! …
```
=> updating the duka receipt

duka-receipts/dukaReceipts.js, duka-receipts/dukaReceipts.test.js
*behaviors before the fix*
- total cost was a total of unit prices
*behaviors after the fix*
- total cost is a sum of products of unit price and quantities for all products
test from [telerivet](https://telerivet.com/p/070b4dfe/service/SVa812d22fe05420dd)
=> Fix duka receipt

notifications/elk-notification/elkNotification.js, notifications/elk-notification/test.js, package-lock.json, setupTests.js, tz-legacy/TanzaniaMain.js
Mimic the webhook to send elk notifications where we want from the codebase. started with Tanzania
=> Bi2 290 not receiving last message ussd

transaction-history/transactionHistory.js, transaction-history/transactionHistory.test.js
I had left  out detection of non numeric characters. this shows an error message in such siituations
=> Hotfix SER-40 show error message if selection is an invalid character

rw-legacy/core.js
Updating master to have the chicken service table id.
Can be tested here: https://telerivet.com/p/8799a79f/service/SV1161debc042a9de0/edit with the account number 24450523
=> added the chicken table id

notifications/elk-notification/elkNotification.js
Updated the JSON sent to ELK to according to the format required. Contact as an object
=> updated the JSON contact object

rw-legacy/core.js
This adds roster_read_key to service variables on rw-lagacy
=> adding the roster read key to rwanda legacy service variables

ke-legacy/main.js
Defined the contact language at the main to see if it resolve the problem
=> define the language at the begining of the service

ke-legacy/main.js
replaced the contact vars with the state vars and defined state.vars.menu
=> removed the contact vars and defined state.vars.main

ke-legacy/main.js
This adds the changes from the [old repo](https://github.com/TomVrankenOAF/KE_USSD) to this one. In particular it adds the changes from the two PRs below.
1.  https://github.com/TomVrankenOAF/KE_USSD/pull/81
2.  https://github.com/TomVrankenOAF/KE_USSD/pull/82
far as I could tell these were the only two changes that were not included when we copied the Repo for Kenya
=> SER-163 sync new repo with old

package.json, tester-pack/inputHandlers/testerPackMenuHandler.js, tester-pack/inputHandlers/testerPackMenuHandler.test.js, tester-pack/status/inputHandlers/nextScreenHandler.test.js, tester-pack/status/inputHandlers/nextScreensHandler.js, tester-pack/status/inputHandlers/registeredConfirmed.test.js, tester-pack/status/inputHandlers/registeredConfirmedHandler.js, tester-pack/status/inputHandlers/villageIdHandler.js, tester-pack/status/inputHandlers/villageIdHandler.test.js, tester-pack/status/status.js, tester-pack/status/status.test.js, tester-pack/status/translations/index.js, tester-pack/testerPack.js, tester-pack/testerPack.test.js
This shows the farmer, how many farmers have registered and confirmed the reception of the tester pack.
test from this[ telerivet link](https://telerivet.com/p/4bee87c0/service/SVa2e7a19f20dc2bc8)
- After dialing in the short code, 
- choose option 4 on the second page
- choose option 3 for status
**villageid**: **11010606**
the next is the summary that shows the number of registered and the number of confirmed.
- choose 1 to see a list of all registered farmers
- choose 2 to see a list of confirmed farmers 
on any list if there are more than one page, there is an option to go next  page (*)
=> Farmer promoter progress

rw-legacy/extension-survey.js, tester-pack/inputHandlers/testerPackMenuHandler.js, tester-pack/inputHandlers/testerPackMenuHandler.test.js, tester-pack/registration/testerPackRegistration.js, tester-pack/registration/testerPackRegistration.test.js, tester-pack/registration/translations/index.js
migrating tester pack registration from extension survey main menu to tester pack menu
Use village id **11010606** to register farmers
test from [telerivet](https://telerivet.com/p/4bee87c0/service/SVa2e7a19f20dc2bc8/edit)
=> Migrate tester pack registration to tester pack menu

.github/workflows/lint.yml, .github/workflows/test.js.yml, package.json, readme.md
We've increased our test coverage, this sets the new threshold to our current coverage so we never go below it
=> Update testing thresholds

rw-legacy/extension-survey.js
=> production variable name fix

logger/elk/elk-logger.js, logger/elk/test.js, package-lock.json, package.json, rw-legacy/lib/roster/register-client.js, setupTests.js
This adds an ELK logger that can post logs, warnings and errors to elk.
=> SER-157 adds elk logger

tz-legacy/TanzaniaMain.js
Use account number: 10803186
**old implementation:** 
- https://telerivet.com/p/5a6ae98f/service/SV8a281edf81d7353a/edit
recently, user would dial the ussd, and get a menu that:
- prompts for the account number
- give options: 1) request for callback 2) How to make a restoration
this resulted into a scenario where users end up requesting for call back accidentally
___________________
Use account number: 10803186
**new implementation:**
https://telerivet.com/p/5a6ae98f/service/SV234ba618164d51a4/edit
- dial in the ussd
- there request callback option is migrated to option 3
- by clicking option 1 you should be prompted for account number
this will reduce the unwanted callback requests.
=> reordering the TZ USSD menu to reduce unnecessary call volumes on callback requests

tz-legacy/TanzaniaMain.js
for the given account number, this user has been active for three seasons namely 2021, 2020 and 2019
- 2021 being the most recent and having a balance of 148600
- 2020 being the second most recent with balance 31758
- 2019 being the oldest but with balance 0. meaning the debt is fully paid
therefore, 2020 is the oldest unrepaid season.
**old implementation**
https://telerivet.com/p/5a6ae98f/service/SV8a281edf81d7353a/edit
when a user request to see balance on Tanzania service, they get balance of the most recent season.
being 2021 with balance 148600
stakeholders have requested to change to a 
**new implementation**
https://telerivet.com/p/5a6ae98f/service/SV53d2a59fac258f53/edit
- choose option 1 to add account number
- add the account number(10069142)
- choose …
=> display the oldest unrepaid season first

chicken-services/change-order-confirmation/index.js, chicken-services/change-order-confirmation/test.js, chicken-services/change-order-handler/index.js, chicken-services/change-order-handler/test.js, chicken-services/index.js, chicken-services/place-order-handler/index.js, chicken-services/place-order-handler/test.js, chicken-services/possible-order-handler/index.js, chicken-services/possible-order-handler/test.js, chicken-services/test.js, ke-legacy/main.js, rw-legacy/core.js, rw-legacy/pshops.js, transaction-history/display-transactions/displayTransactions.js
BI2-302: add webhook function to RW USSD service
BI2-300: add webhook function to P-Shops service
=> added elk notification to rw-core and p-shops

.gitignore, azure-pipelines.yml, package-lock.json, package.json
This adds azure pipelines checks to the repo. It comes with more detailed coverage reporting as you can see [here](https://dev.azure.com/OAFDev/prd-pipelines/_build/results?buildId=2280&view=codecoverage-tab).
Once merged to develop and Master I'll remote the github actions requirements and code.
=> SER-186 Set up CI with Azure Pipelines

Roster-endpoints/Fo-info/getFoInfo.js, Roster-endpoints/Fo-info/getFoInfo.test.js, chicken-services/chicken-eligibility/index.js, chicken-services/chicken-eligibility/test.js, logger/data-table/request-logger.js, logger/data-table/request-logger.test.js, logger/elk/elk-logger.js, logger/elk/elk-logger.test.js, rw-legacy/lib/account-verify.js, rw-legacy/lib/roster/register-client.js, setupTests.js, transaction-history/get-transaction-history/getTransactionHistory.js, transaction-history/get-transaction-history/getTransactionHistory.test.js
Replaces several instances of slack logging with elk logging and updates elk logging.
This PR is reviewable by commit; To review by commit, you can start [here](https://github.com/one-acre-fund/ussd-sms/pull/95/commits/ee3dd62ef2deed1c43f5546d9351379d4f513ebf)
=> SER-157  replaces more slack logs with elk

.eslintrc.js, beyonic-update-retry/beyonicUpdateRetry.js, beyonic-update-retry/beyonicUpdateRetry.test.js, package-lock.json, package.json, setupTests.js
Moved the following service: https://telerivet.com/p/0c6396c9/service/SVe189af5831300300/edit from Telerivet to the codebase
Testing link: https://telerivet.com/p/0c6396c9/service/SV6e35fed0d513d236/edit
The service update columns in the default service table 'Client Portal 2.0' depending on the errors coming from Beyonic and sends the clients updates on the error.
=> Moving beyonic update code

buyback-transactions/buyBackTransactions.js, buyback-transactions/buybackTransactions.test.js, buyback-transactions/inputHandlers/cropsInputHandler.js, buyback-transactions/inputHandlers/cropsInputHandler.test.js, buyback-transactions/inputHandlers/kgsInputHandler.js, buyback-transactions/inputHandlers/kgsInputHandler.test.js, buyback-transactions/inputHandlers/phoneNumberHandler.js, buyback-transactions/inputHandlers/phoneNumberHandler.test.js, buyback-transactions/inputHandlers/varietiesInputHandler.test.js, malawi/MalawiMain.js, malawi/MalawiMain.test.js, malawi/inputHandlers/accountNumberInputHandler.js, malawi/inputHandlers/accountNumberInputHandler.test.js, malawi/inputHandlers/inputHandlers.js, malawi/inputHandlers/inputHandlers.test.js, malawi/validateProjectVariables.js, malawi/validateProjectVariables.test.js
SER-171 recording buyback transactions into a data Table
The short code for malawi got live. hence since the service was developed without testing on the simulator, a few issues came. so this PR fixes those issues.(mostly about data tables)
test from here
https://telerivet.com/p/81cb7b0e/service/SVad79f2b2f69b899d/edit
account number: 10049849
phone number: 0993452454 or 0883452454 or any 10 digits phone number starting with 099 or 088
=> bug-fix malawi buyback transactions

.gitignore, logger/elk/elk-logger.js, logger/elk/elk-logger.test.js
Stringifies the payload being sent to elk
=> Hotfix - SER-222 fix elk logs

ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/mainMenu.js, maize-recommendation/translations/index.js, maize-recommendation/triggerService.js, maize-recommendation/triggerService.test.js
this is the first part of the maize recommendation all it does is it triggers the 2 way messages services. but since the service is not live yet, it can't be triggered. so it will log the error on slack that it can't trigger a non-live service
test from here
https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
account number: 26215997
maize recommendation is option 11 on screen 2.
=> Ser 219 maize recommendation

TEST-RESULTS.xml, chicken-services/chickenServices.js, chicken-services/chickenServices.test.js, chicken-services/translations.js
Replaced few translations in the chicken services as required from :[here](https://docs.google.com/spreadsheets/d/1vDY7HB7ezomiycTj3jOHbBALTojl3HDHSwrew_VGl6s/edit#gid=1895860198)
=> replaced translations

.eslintrc.js, ke-legacy/main.js
Found some functions that were declared twice, this should stop us from making common mistakes in the main file in kenya legacy main file. For an easier time reviewing look at the commits can test that it still works here: https://telerivet.com/p/0c6396c9/service/SV7a3fa65de30127c9/edit
=> Fix lint errors in ke-legacy/main

repayments/repayments.js, repayments/repayments.test.js, repayments/translations/index.js, repayments/validateProjectVariables.js, repayments/validateProjectVariables.test.js, shared/rosterApi/getPhoneNumber.js, shared/rosterApi/getPhoneNumber.test.js
SER-15
As an SHS client, I want to receive a notification that lets me know when I can unlock my SHS, so that I can retrieve my unlock code via USSD
new implementation https://telerivet.com/p/0c6396c9/service/SV412b9240c4f8eea5/edit
old implementation https://telerivet.com/p/0c6396c9/service/SV5d0fbfa8b9a209ae
- moving the kenya mobile money repayment receipt from telerivet to the repo
- sending notification once the user pays the loan in full
the current mock data on the service covers all of those cases and after simulating the service, you should receive 2 messages
1.  repayment notification
2. shs notification
=> SHS client notification SER-15

agrodealer-locator/agrodealerLocator.js, agrodealer-locator/agrodealerLocator.test.js, agrodealer-locator/getSectors.js, agrodealer-locator/getSectors.test.js, agrodealer-locator/inputHandlers.js/districtInputHandler.js, agrodealer-locator/inputHandlers.js/districtsInputHandler.test.js, agrodealer-locator/inputHandlers.js/sectorInputHandler.js, agrodealer-locator/inputHandlers.js/sectorInputHandler.test.js, agrodealer-locator/translations/index.js, rw-legacy/lib/utils/message-translations.js, rw-legacy/pshops.js
Agrodealer locator
https://telerivet.com/p/PShop/service/SV567cd9b2c2081069/edit
testing on telerivet:
- dial in the short code for Rwanda pshop
- choose zero from the main menu to access the pshop's locator
- choose any of the districts (1,2,3). The option 4 is there in case the users don't find their district hence they can get an appropriate message;
- after choosing a district, there is a list of sectors in that district.
- choose a sector
- you should see a screen showing the location and the contact of the agrodealer
- one message should be sent to the farmer, and another to the credit officer.
=> Ser 225 agrodealer locator

repayments/repayments.js, repayments/repayments.test.js
this is an estimate fix for the autosave.
considering that autosave alert from `https://telerivet.com/p/0c6396c9/service/SV865ee2e230f43b24/edit`
queries the messages by message type, and routeIdPush, I have added those fields to the message object.
=> adding the route and message type

transaction-history/get-transaction-history/getTransactionHistory.js, transaction-history/get-transaction-history/getTransactionHistory.test.js
Telerivet does not support large variables.
=> HOTFIX SER-242 limit client transaction history length to 20

CHANGELOG.md, CONTRIBUTING.md, readme.md
Adds a change log and contributing guide to the repo
=> Repo documentation

just-in-time/bundle-choice-handler/bundleChoiceHandler.test.js, just-in-time/order-confirmation-handler/orderConfirmationHandler.test.js, just-in-time/variety-choice-handler/varietyChoiceHandler.test.js, just-in-time/variety-confirmation-handler/varietyConfirmationHandler.test.js, notifications/elk-notification/elkNotification.js, notifications/elk-notification/test.js
This PR is for saving requests being sent to ELK as notifications to check if a session might be ending with some not being sent
It can be reviewed through commits below
=> Log requets to debug

ke-legacy/main.js
When setting the client JSON fails reduce its size. This adds a previously missed check
=> HOTFIX SER-240 reduce the size of account and  balance history

notifications/elk-notification/elkNotification.js, notifications/elk-notification/test.js
=> HotFix-fix

notifications/elk-notification/elkNotification.js, notifications/elk-notification/test.js
=> replaced slack with ELK in ELK notifications

ke-legacy/main.js
Added a new `MainMenuTexWithMsg` function that allows custom message to be displayed on top of the menu.
It is exactly the same as the previous `MainMenuText` function except is remove the length of the custom message from the 140 char limit. If the custom message has more than 50 chars, the first 50 chars are taken.
=> fix option_name from undefined error

notifications/elk-notification/elkNotification.js, notifications/elk-notification/test.js
Added a second retry if the first request timeout on notify ELK
=> added a second try if the first request fails

ke-legacy/main.js
Logs to slack and ELK instead of emails
=> Log errors in sending collection requests

ke-legacy/main.js
Changed the main menu message content, updated the translations
=> Hotfix-changed the menu content

CHANGELOG.md, duka-client/registration/inputHandlers/firstNameInputHandler.js, duka-client/registration/inputHandlers/firstNameInputHandler.test.js, duka-client/registration/inputHandlers/secondNameInputHandler.js, duka-client/registration/inputHandlers/secondNameInputHandler.test.js
[SER-244](https://oneacrefund.atlassian.net/browse/SER-244) Removed special characters for duka registration
=> removed special characters for the duka registration

CHANGELOG.md, ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/mainMenu.js, shared/rosterApi/getProductExpirationInfo.js, shared/rosterApi/getProductExpirationInfo.test.js, warranty-expiration/serial-number-handler/serialNumberHandler.js, warranty-expiration/serial-number-handler/serialNumberHandler.test.js, warranty-expiration/translations.js, warranty-expiration/warrantyExpiration.js, warranty-expiration/warrantyExpiration.test.js
Added check shs warranty expiration option to main meny
Test from here https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit
- Dial in the Kenya short code
- Add account number 26242300
- Go to next page by choosing option 77
- Choose option 12 for Check SHS warranty expiration.
- Enter serial number 18989707
- There will also be a notice telling you whether the product has expired or not along with the date of expiration.
=> SER-17 add check shs warranty expiration

CHANGELOG.md, duka-client/registration/inputHandlers/accountNumberInputHandler.js, duka-client/registration/inputHandlers/accountNumberInputHandler.test.js, duka-client/registration/inputHandlers/confirmFirstSecondNameInputHandler.js, duka-client/registration/inputHandlers/confirmInvoiceIdInputHandler.js, duka-client/registration/inputHandlers/secondNameInputHandler.js, duka-client/registration/inputHandlers/secondNameInputHandler.test.js, duka-client/registration/inputHandlers/transactionTypeInputHandler.js, duka-client/registration/inputHandlers/transactionTypeInputHandler.test.js, duka-client/registration/registration.js, duka-client/registration/registration.test.js, duka-client/registration/translations/index.js, rw-legacy/lib/utils/message-translations.js
Master backmerge of the hotfixes into development branch in preparation for the deployment
=> Master backmerge 19 10 20

nutrition-training/nutritionTraining.js, nutrition-training/nutritionTraining.test.js, nutrition-training/responseHandlers/batch1smsResponseHandler.js, nutrition-training/responseHandlers/batch1smsResponseHandler.test.js, nutrition-training/responseHandlers/batch2smsResponseHandler.js, nutrition-training/responseHandlers/batch2smsResponseHandler.test.js, nutrition-training/translations/index.js
After choosing nutrition training from the kenya impact training menu, this service gets triggered
a series of sms will be sent with prompts. responding to the sent prompts will send other sms as described on this user flow
https://docs.google.com/spreadsheets/d/1OKgITxwBWMOwH1W-nT8m5Vm61tMKhl9IpMbEOxrEpnU/edit?ts=5f461ac2#gid=545566324
You can review code through the commits and telerivet actions here https://telerivet.com/p/0c6396c9/service/SV4a9437d2100a778c
=> SER 227 nutrition training 2-way sms

CHANGELOG.md, ke-legacy/main.js, nutrition-training/nutritionTraining.js, nutrition-training/nutritionTraining.test.js, nutrition-training/responseHandlers/batch1smsResponseHandler.js, nutrition-training/responseHandlers/batch1smsResponseHandler.test.js, nutrition-training/responseHandlers/batch2smsResponseHandler.js, nutrition-training/responseHandlers/batch2smsResponseHandler.test.js, nutrition-training/translations/index.js, nutrition-training/triggerService.js, nutrition-training/triggerService.test.js
After choosing nutrition training from the kenya impact training menu, this service gets triggered
a series of sms will be sent with prompts. responding to the sent prompts will send other sms as described on this user flow
https://docs.google.com/spreadsheets/d/1OKgITxwBWMOwH1W-nT8m5Vm61tMKhl9IpMbEOxrEpnU/edit?ts=5f461ac2#gid=545566324
You can review code through the commits and telerivet actions here https://telerivet.com/p/0c6396c9/service/SV4a9437d2100a778c
=> Ser 227 nutrition training 2

CHANGELOG.md, ke-legacy/main.js
Service: https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit
1. Enter account number
2. Enter 9 to select the "Contact Call center" option
3. Enter 6 to select the "Help on enrollment issues" option
4. A verification message should be returned.
=> Add report enrollment issues option

CHANGELOG.md, azure-pipelines.yml, package.json
* [SER-190](https://oneacrefund.atlassian.net/browse/SER-190) Updated Test Coverage Thresholds
* [SER-190](https://oneacrefund.atlassian.net/browse/SER-190) Added test coverage details to [azure devops](https://dev.azure.com/OAFDev/prd-pipelines/_build/results?buildId=3681&view=codecoverage-tab)
* Fixed Changelog formating
=> updated test thresholds

CHANGELOG.md, kenya-trainings-menu/createMenu.js, kenya-trainings-menu/createMenu.test.js
https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
- dial in the shortcode
- enter the account number: 28126392
- enter 4 for trainings
- select any training (before, after selecting the training, you were taken back to the trainings menu)
but after the fix, you can now go straight to the select training
=> Ser 308 fix trainings menu

CHANGELOG.md, duka-client/registration/inputHandlers/confirmFirstSecondNameInputHandler.js, duka-client/registration/inputHandlers/confirmFirstSecondNameInputHandler.test.js, duka-client/registration/translations/index.js, package-lock.json, package.json, shared/rosterApi/registerClient.js, shared/rosterApi/registerClient.test.js
https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
- enter the credit officer id:  1234
- choose 1 for registration
- choose 0 for new client
- once prompted for national ID enter: **11997754**
- respond to all prompts
since this NID is associated with an account in roster, it will respond with **Client is already enrolled. account number: 28126595**
=> HOTFIX SER-316 Add a descriptive feedback when the registration fails

CHANGELOG.md, ke-legacy/main.js, package-lock.json, package.json
https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit
Dial in the USSD
- add account number 26215997
- choose 8 on the main menu for insurance
- choose 1 for View NHIF Accredited
- choose any region
- from that region, there will come a list of towns (Choose any town)
- there should be a list of hospitals in that town
=> HOT-FIX SER-314 fix NHIF hospital access

CHANGELOG.md, ke-legacy/main.js, package-lock.json, package.json
https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit
check [here](https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit)
- checking balance on the Kenya main menu (option 2) was throwing a translator error hence terminating the service
however, it worked well using english, it only errored while using swahili
Test [here ](https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e/edit)
checking balance should work well for all languages
=> HOTFIX- SER-317 fix kenya check balance

CHANGELOG.md, kenya-trainings-menu/createMenu.js, kenya-trainings-menu/createMenu.test.js, kenya-trainings-menu/options.js, kenya-trainings-menu/options.test.js
Service: https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit
1. Enter account number
2. Enter 4 to select the "Training" option
3. Other training options should be hidden except Soil Training
=> add disable feature for training menu

CHANGELOG.md, ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/mainMenu.js, ke-legacy/utils/menus/populate-menu/nonClientMainMenu.js, seed-germination-issues/inputHandlers/customSeedBrandInputHandler.js, seed-germination-issues/inputHandlers/customSeedBrandInputHandler.test.js, seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.js, seed-germination-issues/inputHandlers/customSeedVarietyInputHandler.test.js, seed-germination-issues/inputHandlers/dukaInputHandler.js, seed-germination-issues/inputHandlers/dukaInputHandler.test.js, seed-germination-issues/inputHandlers/lotCodeInputHandler.js, seed-germination-issues/inputHandlers/lotCodeInputHandler.test.js, seed-germination-issues/inputHandlers/monthInputHandler.js, seed-germination-issues/inputHandlers/monthInputHandler.test.js, seed-germination-issues/inputHandlers/phoneNumberInputHandler.js, seed-germination-issues/inputHandlers/phoneNumberInputHandler.test.js, seed-germination-issues/inputHandlers/registerInputHandlers.js, seed-germination-issues/inputHandlers/registerInputHandlers.test.js, seed-germination-issues/inputHandlers/seedBrandInputHandler.js, seed-germination-issues/inputHandlers/seedBrandInputHandler.test.js, seed-germination-issues/inputHandlers/seedVarietyInputHandler.js, seed-germination-issues/inputHandlers/seedVarietyInputHandler.test.js, seed-germination-issues/inputHandlers/weekInputHandler.js, seed-germination-issues/inputHandlers/weekInputHandler.test.js, seed-germination-issues/seedGerminationIssues.js, seed-germination-issues/seedGerminationIssues.test.js, seed-germination-issues/translations/index.js, shared/createMenu.js, shared/createMenu.test.js
TEST from [here](https://telerivet.com/p/0c6396c9/service/SV7684c662f118f82e)
This functionality can be accessed on the clients menu and non-clients menu
- **change the route to `+254711082882`**
- change the language (optional)
- add account number (26215997)
- choose option 13(Report Seed Quality Issue) from the last screen
- respond to all prompts (lot code is any random number, brand and variety can be entered displayed on option or entered manually once you choose )
after entering the phone number, all entered details will be recorded into the table `https://telerivet.com/p/0c6396c9/data/dev_5Fseed_5Fgermination_5Fissues` 
- **change the route to `+254711082882`**
- change the language (optional)
- choose option 4(Report Seed Quality …
=> SER-275 Reporting seed germination issues

CHANGELOG.md, group-repayments/inputHandlers/lastFourIdDigitsHandler.js, group-repayments/inputHandlers/lastFourIdDigitsHandler.test.js, package-lock.json, package.json
> Service: https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit
1. Dial in short code `*689#`
2. Enter account number `12336313`
3. Select menu option `11` to go to group repayments
4. Enter last 4 digits of national ID `4219`
5. The returned group repayments have no duplicate member.
=> HOTFIX: reduce group size by removing duplicates

CHANGELOG.md, ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/nonClientMainMenu.js, tz-legacy/TanzaniaMain.js
https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit
- Dial in the ussd
- enter 99 to change the laguage to english(optional)
- enter 0(zero) to access the non client's menu
- enter 5 to access the issues menu
- choose any issue among the listed
There should be a notice telling you that the issue was submitted and you will be called within 48 hours.
Finishes 
- [SER-278](https://oneacrefund.atlassian.net/browse/SER-278)
- [SER-277](https://oneacrefund.atlassian.net/browse/SER-277)
=> SER-227 As a OAF non client, I want to be able to access CE services through the USSD system so that I can report issues.

CHANGELOG.md, duka-client/inputHandlers/mainMenuInputHandler.js, duka-client/inputHandlers/mainMenuInputHandler.test.js, package-lock.json, package.json
https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit
- dial in the ussd
- enter 99 to change the language (optional)
- add the credit officer id (1234)
- there is a prompt for registration
(currently if you add 1 everything works well)
but if you add something else, the session gets terminated
FIX: if you add something else except 1, the menu will reprompt for the registration and if you add 1, it will continue with the registration
=> HOT-FIX SER-331 fixing the duka client

CHANGELOG.md, duka-client/registration/inputHandlers/accountNumberInputHandler.test.js, duka-client/registration/translations/index.js, package-lock.json, package.json
[SER-347](https://oneacrefund.atlassian.net/browse/SER-347) show amount to pay in Swahili translation
to test here: https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit
**Do not change the language**
Enter the credit officer number: **1234**
Choose **1** to register a client
Enter the account number: **26916340**
A message should show up with how much to pay
It doesn't happen here: https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit
=> HotFix-SER-347-fixed sw translation

CHANGELOG.md, ke-legacy/main.js
This updates the current and last seasons for Kenya. These variables are used by the SHS feature to determine if a client qualifies for an SHS unit or not
=> updated current and last seasons

CHANGELOG.md, package-lock.json, package.json, rw-legacy/core.js
allowing any other character to act as * on group codes
=> Hotfix-THD-3792-group codes

CHANGELOG.md, avocado-trees-ordering/avocadoTreesOrdering.js, avocado-trees-ordering/avocadoTreesOrdering.test.js, avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.js, avocado-trees-ordering/confirm-order-handler/confirmOrderHandler.test.js, avocado-trees-ordering/place-order-handler/placeOrderHandler.js, avocado-trees-ordering/place-order-handler/placeOrderHandler.test.js, chicken-services/change-order-confirmation/changeOrderConfirmation.js, chicken-services/change-order-confirmation/changeOrderConfirmation.test.js, chicken-services/change-order-handler/changeOrderHandler.js, chicken-services/change-order-handler/changeOrderHandler.test.js, chicken-services/chickenServices.js, chicken-services/chickenServices.test.js, chicken-services/place-order-handler/placeOderHandler.test.js, chicken-services/place-order-handler/placeOrderHandler.js, chicken-services/possible-order-handler/possibleOrderHandler.js, chicken-services/possible-order-handler/possibleOrderHandler.test.js, rw-legacy/core.js
https://telerivet.com/p/8799a79f/service/SV215b0cbe269df25d/edit
- dial in the shortcode
- there should be no displayed option to change the language however, entering 99 will toggle the laguage (English - Kinyarwanda);
- add the account number `24046873` to navigate various services with English.
=> SER-353 change language

CHANGELOG.md, fo-details/foDetails.js, fo-details/foDetails.test.js, fo-details/translations.js, ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/mainMenu.js
Test Service: https://telerivet.com/p/0c6396c9/service/SVea040ce197886f68/edit
1. Login with an account number.
2. The FO Details option should appear in the splash menu.
3. Selecting the FO Details option should return the FO Name and phone number.
=> add get FO details to menu

CHANGELOG.md, recurring-services/cleanup-callback-ussd/cleanupCallBackUSSD.js, recurring-services/cleanup-callback-ussd/cleanupCallBackUSSD.test.js
A telerivet recurring service that cleans up records older than 2 days from the CallBackUSSD datatable daily.
https://telerivet.com/p/0c6396c9/service/SV73198cba51305971/edit
=> auto cleanup callback ussd datatable

CHANGELOG.md, ke-legacy/main.js, ke-legacy/utils/menus/populate-menu/mainMenu.js
you can test from here
https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61
- dial the short code
- enter the account number 13983972
- if (you have set service.vars.env to `dev` report seed quality issues will be on the menu as option 15 otherwise it will not be on the menu i.e if the service.vars.prod is set to prod)
=> MOB-83 Remove "Report Seed Quality Issue" from USSD main Menu ( KE)

CHANGELOG.md, chicken-services/chickenServices.js, group-repayments/inputHandlers/individualBalanceHandler.js, group-repayments/inputHandlers/individualBalanceHandler.test.js, group-repayments/inputHandlers/lastFourIdDigitsHandler.js, group-repayments/translations/message-translations.js, ke-legacy/main.js, rw-legacy/core.js, rw-legacy/lib/utils/message-translations.js, transaction-history/display-transactions/displayTransactions.js, transaction-history/display-transactions/displayTransactions.test.js, transaction-history/transactionHistory.js, transaction-history/transactionHistory.test.js, transaction-history/translations.js
test link: https://telerivet.com/p/8799a79f/service/SV0f1e9ba5632d5274/edit
Use the account number:28951336
Choose option 7 for transaction history
Use 2012 for password
you should be able to navigate forward and backward
Use the account number: 28951336
Choose option 6 for group repayment
Use 2012 for password
overpaid should be added to the info shown and balance should be zero instead of negative
=> MOB-128- back navigation, added overpayment, set balance = 0

CHANGELOG.md, maize-recommendation/responseHandlers/acresResponseHandler.js, maize-recommendation/responseHandlers/acresResponseHandler.test.js, maize-recommendation/responseHandlers/districtResponseHandler.js, maize-recommendation/responseHandlers/districtResponseHandler.test.js, maize-recommendation/responseHandlers/maizeResponseHandler.js, maize-recommendation/responseHandlers/maizeResponseHandler.test.js, maize-recommendation/responseHandlers/seasonHandler.js, maize-recommendation/responseHandlers/seasonHandler.test.js, package-lock.json, package.json
The following error message was received via Email
maize_recommendation was unable to automatically process an incoming SMS from 254708160622:
TypeError: Cannot call method "trim" of null (districtResponseHandler.js#11)
this was caused by the empty input supplied to the input handlers.
=> HOT-FIX MOB-146 maize_recommendation was unable to automatically process an incoming SMS

CHANGELOG.md, group-repayments/inputHandlers/lastFourIdDigitsHandler.js, package-lock.json, package.json
To test  [here](https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit) :
- Enter account number: **21237108**
- Choose option 12 for Group Repayment
- Enter the national Id last digit: **0621**
You should see the group summary 
The same process fails because of the leading zero [here](https://telerivet.com/p/0c6396c9/service/SVbc04709b5abb48c0/edit)
=> HOTFIX- MOB-159-KE-GLs access the Group Repayment Summary Fix

CHANGELOG.md, client-enrollment/clientEnrollment.test.js, client-enrollment/translations.js, just-in-time/account-number-handler/accountNumberHandler.test.js, just-in-time/translations.js, package-lock.json, package.json
To test [here](https://telerivet.com/p/0c6396c9/service/SVc3c8d451e239d756/edit)
Enter GL account number: **27834415**
choose option 4 to TopUp
Enter the account number: **31260975**
you should see a message saying: _Thank you! You have already topped-up with a maximum of three JiT products._
Enter GL account number: **27834415**
choose option 3 for JiT registration
Enter the account number:  **31667965**
you should see a message saying: _Thank you! You have already Enrolled with a maximum of three products._
=> SER-407-changed displaying message in jit

CHANGELOG.md, package-lock.json, package.json, rw-legacy/lib/psh-reg-check.js, rw-legacy/lib/psh-serial-verify.js
test from [here](https://telerivet.com/p/PShop/service/SV567cd9b2c2081069/edit)
- Add account number 30255043
- choose option 2 for SHS
- it asks for serial number, add 17110272
- it should display activation code: 153553435342255
upon repeating the process, it should give the activation code without asking for the serial number since it was registered on the first try.
=> HOT-FIX MOB-371 RW SHS Clients Unable to receive activation code for SHS Units

CHANGELOG.md, kenya-trainings-menu/options.js, package-lock.json, package.json
removing the Kenya impact training (soil fertility) and maize recommendation which was removed by changing it end date in project variables to 8th Feb 2020.
=> HOTFIX: THD-5109 Deactivation of Impact trainingS

CHANGELOG.md, package-lock.json, package.json, rw-legacy/extension-survey.js, rw-legacy/lib/ext-check-stop.js
test from [here](https://telerivet.com/p/4bee87c0/service/SVfc93f479582d4178/edit)
- dial in the shortcode
- choose 2 for the survey quiz
- choose 2 for crops (ama2)
- enter test village id: 10000000
- choose any crop on the list
- there should be a series of questions. answer them randomly
-  after answering like three questions (dial in 9999 or just click cancel on the simulator to drop the call or drop the call manually. )
- repeat the process 
- (user should continue from where they left off if they choose the same crop again)
=> HOTFIX: MOB-145 RW crop survey

CHANGELOG.md, package-lock.json, package.json, shs/helper-functions/getCode.js, shs/helper-functions/getCode.test.js, shs/helper-functions/registerSerialNumber.js, shs/helper-functions/registerSerialNumber.test.js, shs/shs.js, shs/translations.js
To test [here](https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit)
Use account number: 21600686
Choose solar option
Register a new serial number: 57192650
**This works even though that client did not place an order in the current season**
The same fails [here](https://telerivet.com/p/0c6396c9/service/SV9c1a4577fb4b6b47/edit)
=> HOTFIX-MOB-405-MOB-406-add call vars for elk and changed payment calculation shs

CHANGELOG.md, package-lock.json, package.json, rw-legacy/traffic-alert.js
This list is updated so as the list of admin email and name dataTable is https://telerivet.com/p/8799a79f/data/admin_5Femails
=> HOT-FIX ESWFA-53 Monitoring tool for Telerivet to track USSD downtime from Africa's talking in Rwanda

CHANGELOG.md, ke-legacy/main.js, kenya-trainings-menu/options.js, package-lock.json, package.json
test from [here](https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit)
- click the call button on the simulator
- you can change the language by 99
- enter 0 (zero) to access the non-client menu
- choose option 2 for find training
- from the list of trainings, you can select any of them. this should trigger a 2 way SMS service, but it can't be demoed on the simulator but there comes a popup like this
```
A training SMS has been sent to your phone. Messages are free! But please delete unwanted SMS in your phone to make space for incoming.
=> HOTFIX-ESWFA-102 switching on the kenya impact trainings

CHANGELOG.md, contact-call-center/contactCallCenter.test.js, contact-call-center/menuOptions.js, package-lock.json, package.json
Test from [Here](https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit)
- Dial in the ussd
- enter Zero to access the non-client menu
- choose option 4 to go to the call center menu
- enter 77 to go to the next screen
- there should be an option for IPP client Call Back Request
- Upon choosing that option, you should get this
`
You will contacted by our customer service representative within 48 hours. 
Do not switch off this phone or place a duplicate request.`
=> ESWFA-93 Add an IPP option to the non farmer USSD menu

CHANGELOG.md, ke-legacy/main.js, kenya-impact-trainings/inputHandlers/phoneNumberHandler.js, kenya-impact-trainings/inputHandlers/phoneNumberHandler.test.js, kenya-impact-trainings/kenya-impact-trainings.js, kenya-impact-trainings/kenya-impact-trainings.test.js, kenya-impact-trainings/translations/index.js, kenya-impact-trainings/utils/makePhones.js, kenya-impact-trainings/utils/makePhones.test.js, kenya-trainings-menu/options.js, package-lock.json, package.json
test from [here](https://telerivet.com/p/0c6396c9/service/SV3c5034dacfc21c61/edit)
dial in the ussd
* enter 0 to access the non client menu
* choose 2 for trainings
* enter pin number (0716263596) this is the stored phone in the tables, but you should be able to bypass the code validation with any format of the phone
- 716263596
- 0716263596
- 254716263596
- 2540716263596
-  +254716263596
-  +2540716263596
* after, you should be able to access thecurrent 4 trainings
* for a wrong phone you keep being prompted for pin
=> HOT-FIX: THD-5670-Switching on of Training service on USSD & 2-Way SMS

CHANGELOG.md, ke-legacy/main.js, kenya-impact-trainings/inputHandlers/phoneNumberHandler.js, kenya-impact-trainings/inputHandlers/phoneNumberHandler.test.js, kenya-impact-trainings/kenya-impact-trainings.test.js, kenya-impact-trainings/translations/index.js, kenya-impact-trainings/utils/TrainingTriggeredText.js, kenya-impact-trainings/utils/TrainingTriggeredText.test.js, kenya-trainings-menu/options.js, package-lock.json, package.json
dial in the ussd
- enter 0 to access the non clients menu
- choose 2 for trainings
- enter phone: 0700010006 to access trainings menu
- the order of trainings on the menu should be
```
1. Maize intercrop
2. Topdress
3. Pest Mitigation
4. Maize harvest
```
and not any other order
and upon selecting any training, there should be a popup message
```
Congratulations KADIRI, EVANS on your first step towards becoming a smart farmer!
A training SMS has been sent to your phone. Start your learning journey now!
```
instead of
```
A training SMS sent to my phone. 
Messages are free! But please delete SMS in your phone
to make space for incoming messages.
```
=> HOT-FIX ESWFA-113 Fix the Kenya Impact Trainings

CHANGELOG.md, package-lock.json, package.json, shs/endpoints/registerSerial.js, shs/serial-number-handler/serialNumberHandler.js, shs/serial-number-handler/serialNumberHandler.test.js, shs/shs.js, shs/translations.js
To test [here](https://telerivet.com/p/0c6396c9/service/SVb47209de1fdd2cf0/edit)
Enter an  account number: **24450523**
Choose option 5 for Solar
Choose option 1 for Register Solar
Enter existing an already existing shs serial: **10966520** a message saying that they have already registered should come up
Repeat the same steps with a new shs serial number **63466320** a message saying that it's successfully registered shows up
also on this [table](https://telerivet.com/p/0c6396c9/data/ss_2Dtesting_2Doffline_2Dservices) the correct expiration date is saved
=> MOB-408 Change shs displaying message

CHANGELOG.md, package-lock.json, package.json, sbcc/translations/message-translations.js, sbcc/ussd/input-handlers/nationalIdHandler.js, sbcc/ussd/input-handlers/nationalIdHandler.test.js, sbcc/ussd/input-handlers/pinHandler.js, sbcc/ussd/input-handlers/pinHandler.test.js, sbcc/ussd/input-handlers/pinMenuHandler.js, sbcc/ussd/input-handlers/pinMenuHandler.test.js, sbcc/ussd/input-handlers/sbccMenuHandler.js, sbcc/ussd/input-handlers/sbccMenuHandler.test.js
When user has forgotten their national ID or pin, they will no longer be told that a CE Agent will call them in 24 hours. Instead, they will now see a message containing the hotline number, so they can call on their own.
Test [here](https://telerivet.com/p/0c6396c9/service/SV1568896afd0ac1d6/edit)
1. Select SBCC in the Non client menu
2. Select the "I forgot my national ID" option. You should see a message with the hotline number to be called. This should also be the same behaviour when pin is forgotten, and also when a wrong pin or national ID has been entered more than thrice.
=> HOTFIX - Removed call scheduling when national ID or pin is forgotten in SBCC - ESWFA-128

CHANGELOG.md, notifications/elk-notification/elkNotification.js, package-lock.json, package.json, shs/serial-number-handler/serialNumberHandler.js, shs/shs.js
Just changed the names of variables sent to ELK. Call vars with Date as suffix seems to not work on ELK. added new Registration data point too
=> Bi2 593 missing data points

rw-legacy/dat/district-bundles.js, rw-legacy/pshops.js
Added a missing data table-id for bundles in pshops
=> Fixing the Pshops

CHANGELOG.md, avocado-trees-ordering/avocadoTreesOrdering.js, chicken-services/chickenServices.js, client-registration/clientRegistration.js, group-repayments/groupRepayments.js, package-lock.json, package.json, rw-legacy/core.js, rw-legacy/lib/enr-resume-registration.js, rw-legacy/lib/enr-retrieve-client-row.js, rw-legacy/lib/enr-send-order-sms.js, rw-legacy/lib/populate-menu.js, transaction-history/transactionHistory.js
this implementation does not change any implementation, it only optimize the existing one by loading less modules at the beginning of execution.
=> HOTFIX-ESWFA-166 Refactor Rwanda ussd script module

logger/elk/elk-logger.js
Login is failing [Here]:(https://telerivet.com/p/8799a79f/service/SV644286941b72de49/edit) 
this fix can be tested [here](https://telerivet.com/p/8799a79f/service/SV0f1e9ba5632d5274/edit)
=> remove underscore

CHANGELOG.md, package-lock.json, package.json, repayments-rw/repaymentsRw.js
can be tested [here](https://telerivet.com/p/8799a79f/service/SV6fdea5db75a984d5/edit).
Replace the phone number in the contact.phone_number variable with yours and you should see an sms
=> HotFix-THD-442-Rw repayment fix sms route

sbcc/ivr/input-handlers/mainMenuOneHandler.js, sbcc/ivr/input-handlers/mainMenuTwoHandler.js, sbcc/ivr/input-handlers/olderEpisodesMenuHandler1.js, sbcc/ivr/input-handlers/olderEpisodesMenuHandler2.js, sbcc/ivr/input-handlers/selectedTipAndEpHandler1.js, sbcc/ivr/input-handlers/selectedTipAndEpHandler2.js, sbcc/ivr/input-handlers/topTipsMenuHandler1.js, sbcc/ivr/input-handlers/topTipsMenuHandler2.js, sbcc/ussd/input-handlers/pinHandler.js, sbcc/utils/addPlayedItem.js, sbcc/utils/addPlayedItem.test.js
test [here](https://telerivet.com/p/0c6396c9/service/SVa51cccee1d5a5b07/edit) and play some episodes and/or top tips
_data.vars.all_items_played_ should have a value on elk
=> append all played episodes and top tips in a call variable - ESWFA-175

CHANGELOG.md, package-lock.json, package.json, repayments-rw/repaymentsRw.test.js, repayments-rw/translations/index.js
can be tested with your your phone number [here](https://telerivet.com/p/8799a79f/service/SV6fdea5db75a984d5/edit)
=> HOTFIX-rename RW repayment season to 2021

CHANGELOG.md, package-lock.json, package.json, rw-legacy/core.js, rw-legacy/lib/utils/message-translations.js
Update the RW registration to continue immediately after registration:
can be tested [here](https://telerivet.com/p/8799a79f/service/SV1161debc042a9de0/edit)
Use any 16 digits for ID,
Use 31646013*00013 for group code 
should be redirected to ordering menu after registration
=> Eswfa 182 continue ordering

rw-legacy/core.js, rw-legacy/lib/get-menu-option.js, rw-legacy/lib/isDistrictClosed.js, rw-legacy/lib/populate-menu.js, rw-legacy/lib/utils/message-translations.js
Can be tested  [here](https://telerivet.com/p/8799a79f/service/SV1161debc042a9de0/edit)
For enrollment use the account number: 24450523 (registered in the district 10646. can change date [here](https://telerivet.com/p/8799a79f/data/District_20Enrollment_20Date) ) **The ordering and finalize option should be hidden on the menu. Also a pop up should show up if they choose those regardless**
For registration, use the group code 1064601602535 (A pop up should show up if they choose to continue to ordering after registration)
=> Eswfa 187 end enrollment in districts

CHANGELOG.md, bu-ussd/enrollment/enrollment.js, bu-ussd/enrollment/inputHandlers/finalizeHandler.js, bu-ussd/enrollment/inputHandlers/finalizeHandler.test.js, bu-ussd/enrollment/translations/index.js, bu-ussd/enrollment/utils/confirmOrder.js, bu-ussd/enrollment/utils/confirmOrder.test.js, bu-ussd/enrollment/utils/onOrderOrFinaliseSelected.js, bu-ussd/enrollment/utils/onOrderOrFinaliseSelected.test.js, bu-ussd/inputHandlers/enrollmentCategoryHandler.js, bu-ussd/inputHandlers/enrollmentCategoryHandler.test.js, bu-ussd/inputHandlers/groupCodeHandler.js, bu-ussd/inputHandlers/groupCodeHandler.test.js, bu-ussd/inputHandlers/mainMenuHandler.js, bu-ussd/inputHandlers/mainMenuHandler.test.js, bu-ussd/inputHandlers/preEnrollmentHandler.js, bu-ussd/inputHandlers/preEnrollmentHandler.test.js, bu-ussd/inputHandlers/registerInputHandlers.js, bu-ussd/main.js, bu-ussd/registration/inputHandlers/registerConfirmationInputHandler.js, bu-ussd/translations/index.js, shared/splitLongMenu.js, shared/splitLongMenu.test.js
https://oneacrefund.atlassian.net/browse/ESWFA-186
=> ESWFA-42-Add bu navigation

CHANGELOG.md, package-lock.json, package.json, rw-legacy/lib/cor-get-balance.js
Test here https://telerivet.com/p/8799a79f/service/SV0f1e9ba5632d5274/edit
dial in the account number: 21955922
- choose 1 for check balance
-the displayed information should be  for the current repayment season 2021
```
Hello M-----I, A------e
Credit:31140
Paid:12291.2
Balance:18848.8
Accurate as of Tuesday 15 June
```
instead of the last repayment season
```
Muraho MUPENZI, Anastase
Ideni ryose:6120
Ayishyuwe:33500
Ideni risigaye:18848
Amafaranga arenga: 27380
Amakuru yafashwe Kuwakabiri 15 Ukwagatandatu
```
=> HOTFIX ESWFA-190 correcting RW - repayment info

CHANGELOG.md, package-lock.json, package.json, rw-legacy/extension-survey.js, rw-legacy/lib/get-menu-option.js, rw-legacy/lib/populate-menu.js
The BUNDLES  table was missing in the service variables of the Rwanda extension survey project hence causing a crash to the whole service whenever someone tried to use it.
=> updating the rwanda survey

rw-legacy/dat/surveys.js, rw-legacy/lib/utils/message-translations.js, tester-pack/confirmation/inputHandlers/receptionHandler.js, tester-pack/confirmation/inputHandlers/receptionHandler.test.js, tester-pack/confirmation/translations/index.js
https://docs.google.com/spreadsheets/d/16nFwcwftzT-MKm07vBavvQOVgpTkcIJxDCOxeIsctHs/edit#gid=450338194
=> HOT-FIX - ESWFA-192 updating the tester pack

CHANGELOG.md, package-lock.json, package.json, tz-legacy/TanzaniaMain.js
changing from 'Boneyeza' to 'Chagua'
=> HOTFIX THD-7875 correcting the tanzanian main menu

chicken-services/chicken-eligibility/chickenEligibility.js
Fixing chicken confirmation
- matching the government (sector and district) with Tubura's
=> Fixing chicken confirmation

chicken-services/check-chicken-cap-by-district/CheckChickenCapByDistrict.js, chicken-services/chicken-eligibility/chickenEligibility.js
marching the chicken table with clients table geo-location
=> removing search by district to search by account number

CHANGELOG.md, repayments-rw/repaymentsRw.js, repayments-rw/repaymentsRw.test.js, repayments-rw/translations/index.js, rw-legacy/core.js, rw-legacy/lib/cor-get-balance.js, rw-legacy/lib/utils/message-translations.js
Adding the last season balance to the balance details in Rwanda
=> THD-8264 USSD Repayment Balance check Issue

CHANGELOG.md, ke-registration-notification/registrationNotification.js, ke-registration-notification/registrationNotification.test.js, ke-registration-notification/translations/index.js
updating the registration sms service to adopt multiple countries
=> THD-7443 Mobile Enrollment-Request change on Account Number SMS Feature-TZ
